package main

import (
	"crypto/ed25519"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/crypto/blake2b"
)

// trustedUpdateKeys are the minisign public keys trusted to authenticate release
// SHA256SUMS files. Each entry is the raw base64 from the second line of a
// minisign `.pub` file (binary layout: algo[2] || key_id[8] || ed25519_key[32]).
//
// It is an array so a key can be rotated without bricking auto-update: publish a
// release signed by the new key, ship a client build that trusts both, then
// retire the old key in a later build.
var trustedUpdateKeys = []string{
	// ArchClash release key (generated by the maintainer 2026-06-06, id 90781719EFA97A1A)
	"RWQaeqnvGRd4kI2tkOi4JGfiD5IM5gXw3X5ZJ8cohs0dWAmEoav+AprY",
}

type minisignKey struct {
	keyID [8]byte
	pub   ed25519.PublicKey
}

func parseMinisignPubKey(b64 string) (minisignKey, error) {
	raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(b64))
	if err != nil {
		return minisignKey{}, fmt.Errorf("decode public key: %w", err)
	}
	if len(raw) != 42 {
		return minisignKey{}, fmt.Errorf("public key has wrong length %d (want 42)", len(raw))
	}
	if string(raw[0:2]) != "Ed" {
		return minisignKey{}, fmt.Errorf("unsupported public key algorithm %q", string(raw[0:2]))
	}
	var k minisignKey
	copy(k.keyID[:], raw[2:10])
	k.pub = ed25519.PublicKey(append([]byte(nil), raw[10:42]...))
	return k, nil
}

type minisignSig struct {
	algo            [2]byte // "Ed" (signs raw file) or "ED" (signs blake2b-512 of file)
	keyID           [8]byte
	sig             []byte // 64-byte ed25519 signature over the (possibly prehashed) message
	trustedComment  string
	globalSignature []byte // 64-byte ed25519 signature over sig || trustedComment
}

// parseMinisignSignature parses a minisign `.minisig` file:
//
//	untrusted comment: <text>
//	<base64: algo[2] || key_id[8] || signature[64]>
//	trusted comment: <text>
//	<base64: global_signature[64]>
func parseMinisignSignature(content []byte) (minisignSig, error) {
	norm := strings.ReplaceAll(string(content), "\r\n", "\n")
	lines := strings.Split(strings.TrimRight(norm, "\n"), "\n")
	if len(lines) < 4 {
		return minisignSig{}, errors.New("signature file truncated (want 4 lines)")
	}
	sigBin, err := base64.StdEncoding.DecodeString(strings.TrimSpace(lines[1]))
	if err != nil {
		return minisignSig{}, fmt.Errorf("decode signature line: %w", err)
	}
	if len(sigBin) != 74 {
		return minisignSig{}, fmt.Errorf("signature has wrong length %d (want 74)", len(sigBin))
	}
	const tcPrefix = "trusted comment:"
	if !strings.HasPrefix(lines[2], tcPrefix) {
		return minisignSig{}, errors.New("missing trusted comment line")
	}
	globalBin, err := base64.StdEncoding.DecodeString(strings.TrimSpace(lines[3]))
	if err != nil {
		return minisignSig{}, fmt.Errorf("decode global signature line: %w", err)
	}
	if len(globalBin) != 64 {
		return minisignSig{}, fmt.Errorf("global signature has wrong length %d (want 64)", len(globalBin))
	}
	var s minisignSig
	copy(s.algo[:], sigBin[0:2])
	copy(s.keyID[:], sigBin[2:10])
	s.sig = sigBin[10:74]
	s.trustedComment = strings.TrimSpace(strings.TrimPrefix(lines[2], tcPrefix))
	s.globalSignature = globalBin
	return s, nil
}

// verifyMinisign verifies a minisign signature over message against the supplied
// trusted public keys (raw base64 .pub values). It returns nil only if the
// signature is valid under one of the trusted keys, including the global
// signature over the trusted comment.
func verifyMinisign(message, sigContent []byte, trustedKeys []string) error {
	sig, err := parseMinisignSignature(sigContent)
	if err != nil {
		return err
	}

	var signed []byte
	switch string(sig.algo[:]) {
	case "Ed": // legacy: signature over the raw file
		signed = message
	case "ED": // prehashed: signature over blake2b-512(file)
		h := blake2b.Sum512(message)
		signed = h[:]
	default:
		return fmt.Errorf("unsupported signature algorithm %q", string(sig.algo[:]))
	}

	var matchedKey bool
	for _, raw := range trustedKeys {
		k, err := parseMinisignPubKey(raw)
		if err != nil {
			continue
		}
		if k.keyID != sig.keyID {
			continue
		}
		matchedKey = true
		if !ed25519.Verify(k.pub, signed, sig.sig) {
			return errors.New("signature does not verify against the trusted key")
		}
		// Defense in depth: the global signature binds the trusted comment.
		global := append(append([]byte(nil), sig.sig...), []byte(sig.trustedComment)...)
		if !ed25519.Verify(k.pub, global, sig.globalSignature) {
			return errors.New("global (trusted comment) signature does not verify")
		}
		return nil
	}
	if !matchedKey {
		return errors.New("signature key id is not in the trusted set")
	}
	return errors.New("signature verification failed")
}
