// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProfile(arg1) {
  return window['go']['main']['App']['ActivateProfile'](arg1)
}

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']()
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']()
}

export function CloseAllConnections() {
  return window['go']['main']['App']['CloseAllConnections']()
}

export function Connect() {
  return window['go']['main']['App']['Connect']()
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1)
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']()
}

export function EnsureTunReady() {
  return window['go']['main']['App']['EnsureTunReady']()
}

export function FetchConnectionsOverview() {
  return window['go']['main']['App']['FetchConnectionsOverview']()
}

export function FetchRulesOverview() {
  return window['go']['main']['App']['FetchRulesOverview']()
}

export function GetAdvancedGeoStatus() {
  return window['go']['main']['App']['GetAdvancedGeoStatus']()
}

export function GetAdvancedPaths() {
  return window['go']['main']['App']['GetAdvancedPaths']()
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']()
}

export function GetDesktopPrefs() {
  return window['go']['main']['App']['GetDesktopPrefs']()
}

export function GetLaunchOnStartupPreference() {
  return window['go']['main']['App']['GetLaunchOnStartupPreference']()
}

export function GetPreferredLanguage() {
  return window['go']['main']['App']['GetPreferredLanguage']()
}

export function GetProfilePaths(arg1) {
  return window['go']['main']['App']['GetProfilePaths'](arg1)
}

export function GetProfileProxyGroupsBaseline(arg1) {
  return window['go']['main']['App']['GetProfileProxyGroupsBaseline'](arg1)
}

export function GetProfileRulesBaseline(arg1) {
  return window['go']['main']['App']['GetProfileRulesBaseline'](arg1)
}

export function GetRuntimeDiagEvents() {
  return window['go']['main']['App']['GetRuntimeDiagEvents']()
}

export function GetSubscriptionDeviceIdentity() {
  return window['go']['main']['App']['GetSubscriptionDeviceIdentity']()
}

export function GetTrayAvailability() {
  return window['go']['main']['App']['GetTrayAvailability']()
}

export function GetTunStatus() {
  return window['go']['main']['App']['GetTunStatus']()
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']()
}

export function ImportProfileFromText(arg1, arg2) {
  return window['go']['main']['App']['ImportProfileFromText'](arg1, arg2)
}

export function ImportProfileFromURL(arg1, arg2) {
  return window['go']['main']['App']['ImportProfileFromURL'](arg1, arg2)
}

export function InstallService() {
  return window['go']['main']['App']['InstallService']()
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']()
}

export function MarkQuitIntent() {
  return window['go']['main']['App']['MarkQuitIntent']()
}

export function NavigateUIScreen(arg1) {
  return window['go']['main']['App']['NavigateUIScreen'](arg1)
}

export function OnSecondInstance(arg1) {
  return window['go']['main']['App']['OnSecondInstance'](arg1)
}

export function OnWindowBecameVisible() {
  return window['go']['main']['App']['OnWindowBecameVisible']()
}

export function OpenPathInExplorer(arg1) {
  return window['go']['main']['App']['OpenPathInExplorer'](arg1)
}

export function PeekSubscriptionFromURL(arg1) {
  return window['go']['main']['App']['PeekSubscriptionFromURL'](arg1)
}

export function ReExtractBundledResources() {
  return window['go']['main']['App']['ReExtractBundledResources']()
}

export function ReadProfileConfig(arg1) {
  return window['go']['main']['App']['ReadProfileConfig'](arg1)
}

export function ReadServiceLatestLog(arg1) {
  return window['go']['main']['App']['ReadServiceLatestLog'](arg1)
}

export function RefreshHomeInsight() {
  return window['go']['main']['App']['RefreshHomeInsight']()
}

export function RefreshProfileSubscription(arg1) {
  return window['go']['main']['App']['RefreshProfileSubscription'](arg1)
}

export function RefreshProxies() {
  return window['go']['main']['App']['RefreshProxies']()
}

export function RefreshSlothServiceStatus() {
  return window['go']['main']['App']['RefreshSlothServiceStatus']()
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2)
}

export function ResetSubscriptionCache() {
  return window['go']['main']['App']['ResetSubscriptionCache']()
}

export function RestartCore() {
  return window['go']['main']['App']['RestartCore']()
}

export function SelectProxyGroup(arg1) {
  return window['go']['main']['App']['SelectProxyGroup'](arg1)
}

export function SetAppAutoUpdateEnabled(arg1) {
  return window['go']['main']['App']['SetAppAutoUpdateEnabled'](arg1)
}

export function SetCloseToTrayPreference(arg1) {
  return window['go']['main']['App']['SetCloseToTrayPreference'](arg1)
}

export function SetHwidEnabled(arg1) {
  return window['go']['main']['App']['SetHwidEnabled'](arg1)
}

export function SetLaunchOnStartupPreference(arg1) {
  return window['go']['main']['App']['SetLaunchOnStartupPreference'](arg1)
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1)
}

export function SetProfileAutoUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetProfileAutoUpdate'](arg1, arg2, arg3)
}

export function SetProfileMergeTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetProfileMergeTemplate'](arg1, arg2)
}

export function SetProfileProxyTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetProfileProxyTemplate'](arg1, arg2)
}

export function SetProfileRulesTemplate(arg1, arg2) {
  return window['go']['main']['App']['SetProfileRulesTemplate'](arg1, arg2)
}

export function SetProxyNode(arg1, arg2) {
  return window['go']['main']['App']['SetProxyNode'](arg1, arg2)
}

export function SetTrafficMode(arg1) {
  return window['go']['main']['App']['SetTrafficMode'](arg1)
}

export function SetTrafficSettings(arg1) {
  return window['go']['main']['App']['SetTrafficSettings'](arg1)
}

export function SetTunSettings(arg1) {
  return window['go']['main']['App']['SetTunSettings'](arg1)
}

export function SetUiLanguage(arg1) {
  return window['go']['main']['App']['SetUiLanguage'](arg1)
}

export function SetUpdateChannel(arg1) {
  return window['go']['main']['App']['SetUpdateChannel'](arg1)
}

export function StartedMinimized() {
  return window['go']['main']['App']['StartedMinimized']()
}

export function TestProxyDelay(arg1) {
  return window['go']['main']['App']['TestProxyDelay'](arg1)
}

export function UpdateProfileInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfileInfo'](arg1, arg2, arg3)
}

export function UpdateRuleProvider(arg1) {
  return window['go']['main']['App']['UpdateRuleProvider'](arg1)
}

export function WriteProfileConfig(arg1, arg2) {
  return window['go']['main']['App']['WriteProfileConfig'](arg1, arg2)
}
